name: Calcular edad de una persona en base a su fecha de nacimiento

on:
  workflow_dispatch:
    inputs:
      dia_nacimiento:
        description: 'Dia de nacimiento'
        required: true
        type: string
      mes_nacimiento:
        description: 'Mes de nacimiento'
        required: true
        type: string
      anio_nacimiento:
        description: 'Año de nacimiento'
        required: true
        type: string

jobs:
  calcular_edad:
    name: Calcular edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.calcular_edad.outputs.edad }}
    steps:
      - name: Calcular edad
        id: calcular_edad
        run: |
          anio_nacimiento=${{ github.event.inputs.anio_nacimiento }}

          fecha_nacimiento="$anio_nacimiento"
          fecha_actual=$(date +%Y)

          edad=$( $(date -d "$fecha_actual" +%s) - $(date -d "$fecha_nacimiento" +%s) )

          echo "Edad calculada: $edad años"
          echo "edad=$edad" >> "$GITHUB_OUTPUT"

