name: Calcular edad de una persona en base a su fecha de nacimiento

on:
  workflow_dispatch:
    inputs:
      dia_nacimiento:
        description: 'Dia de nacimiento'
        required: true
        type: string
      mes_nacimiento:
        description: 'Mes de nacimiento'
        required: true
        type: string
      anio_nacimiento:
        description: 'Año de nacimiento'
        required: true
        type: string

jobs:
  calcular_edad:
    name: Calcular edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.calcular_edad.outputs.edad }}
    steps:
      - name: Calcular edad
        id: calcular_edad
        run: |
          dia_nacimiento=${{ github.event.inputs.dia_nacimiento }}
          mes_nacimiento=${{ github.event.inputs.mes_nacimiento }}
          anio_nacimiento=${{ github.event.inputs.anio_nacimiento }}

          fecha_nacimiento=$(date -d "$anio_nacimiento-$mes_nacimiento-$dia_nacimiento" +%s)
          echo "Fecha de nacimiento: $fecha_nacimiento"
          fecha_actual=$(date +%Y-%m-%d)
          echo "Fecha actual: $fecha_actual"

          edad=$(( (fecha_actual - fecha_nacimiento) / 86400 ))

          echo "Edad calculada: $edad años"
          echo "edad=$edad" >> "$GITHUB_OUTPUT"

  mostrar_clasificacion_etapa_de_vida:
    name: Mostrar clasificación de etapa de vida
    runs-on: ubuntu-latest
    needs: calcular_edad
    steps:
      - name: Evaluar edad y mostrar clasificación
        run: |
          edad=${{ needs.calcular_edad.outputs.edad }}

          if [ $edad -le ${{ vars.LIM_NINEZ }} ]; then
            echo "La persona pertenece a la etapa de la Niñez."
          elif [ $edad -le ${{ vars.LIM_ADOLESCENCIA }} ]; then
            echo "La persona pertenece a la etapa de la Adolescencia."
          elif [ $edad -le ${{ vars.LIM_ADULTO_JOVEN }} ]; then
            echo "La persona pertenece a la etapa de los Adultos Jóvenes."
          elif [ $edad -le ${{ vars.LIM_ADULTO }} ]; then
            echo "La persona pertenece a la etapa de los Adultos."
          else
            echo "La persona pertenece a la Tercera Edad."
          fi
