name: convert-json-to-file

on:
  push:
    branches:
      - master

jobs:
  convert_file_to_json:
    runs-on: ubuntu-latest

    steps:
      - name: Convert JSON to file
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: |
            {
              "name": "pipelines",
              "activity": 3,
              "module": 2,
              "isRequired": false
            }
          filename: 'archivo.json'

      - name: Upload JSON file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: archivo-json
          path: archivo.json
