name: Operaciones matematicas paralelas

on:
  workflow_dispatch:
    inputs:
      FIRST_NUMBER:
        description: 'Ingrese el primer número'
        required: true
        type: string
      SECOND_NUMBER:
        description: 'Ingrese el segundo número'
        required: true
        type: string

jobs:
  mathematical_operations:
    name: Calculate mathematical operations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operation: [sum, subtract, multiply, divide]

    env:
      FIRST_NUMBER: ${{ inputs.FIRST_NUMBER }}
      SECOND_NUMBER: ${{ inputs.SECOND_NUMBER }}

    steps:
      - name: Perform ${{ matrix.operation }} operation
        run: |
          num1=${{ env.FIRST_NUMBER }}
          num2=${{ env.SECOND_NUMBER }}

          case ${{ matrix.operation }} in
            sum)
              result=$((num1 + num2))
              echo "Sum: $result"
              ;;
            subtract)
              result=$((num1 - num2))
              echo "Subtract: $result"
              ;;
            multiply)
              result=$((num1 * num2))
              echo "Multiply: $result"
              ;;
            divide)
              if [ $num2 -ne 0 ]; then
                result=$((num1 / num2))
                echo "Divide: $result"
              else
                echo "Error: Division by zero is not allowed."
                exit 1
              fi
              ;;
          esac
